# SPDX-License-Identifier: MIT
- hosts: all
  name: Base tasks (user accounts, important packages)
  tags: base

  tasks:
  - name: Create user accounts
    user:
      name: "{{ item.name }}"
      groups: sudo
      password: ""
      shell: "/bin/bash"
      update_password: on_create
    loop: "{{ users }}"

  - name: Add SSH public key
    authorized_key:
      user: "{{ item.0.name }}"
      key: "{{ item.1 }}"
    loop: "{{ users|subelements('ssh_public_keys') }}"

  - name: Add SSH public keys to root for users with root permissions
    when: item.0.root
    authorized_key:
      user: "root"
      key: "{{ item.1 }}"
    loop: "{{ users|subelements('ssh_public_keys') }}"

  - name: Install sudo
    apt:
      name: sudo

  - name: Install some other utility packages
    apt:
      name: [htop, screen, time, goaccess]
