# SPDX-License-Identifier: MIT
- name: Enable Apache module rewrite and alias
  apache2_module:
    name: '{{ item }}'
    state: present
  loop:
    - rewrite
    - alias
  notify:
    - systemd restart apache2

- name: 'Apache2 redirect 80 → 443: configuration file for inclusion'
  when: "'letsencrypt' in group_names"
  copy:
    dest: '/etc/apache2/sites-available/redirect-http.inc'
    owner: root
    group: root
    mode: 0644
    content: |
      RewriteEngine On
      RewriteCond %{REQUEST_URI} !^/.well-known/acme-challenge
      RewriteCond %{HTTPS} off
      RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI} [R=301,L]
  notify:
    - systemd reload apache2
