#!/bin/bash

set -euo pipefail

echo "Post processing imported data"
cd /opt/OpenRailwayMap-vector/

run_sql() {
    echo "Running $1 ..."
    psql --dbname gis --variable ON_ERROR_STOP=on --pset pager=off -f "$1"
}

# Functions
run_sql import/sql/tile_functions.sql
#run_sql import/sql/api_facility_functions.sql
#run_sql import/sql/api_milestone_functions.sql

# YAML data
run_sql build/signal_features.sql
run_sql build/operators.sql

# Post processing
run_sql import/sql/linking_views.sql
run_sql import/sql/get_station_importance.sql
run_sql import/sql/update_station_importance.sql
echo "Running osm2pgsql-gen ..."
LUA_PATH=/opt/OpenRailwayMap-vector/build/tags.lua osm2pgsql-gen \
  --database gis \
  --style /opt/OpenRailwayMap-vector/import/openrailwaymap.lua
run_sql import/sql/stations_clustered.sql

# Tile and API views on processed data
run_sql import/sql/tile_views.sql
#run_sql import/sql/api_facility_views.sql
