debian_version: buster
pg_version: 11
postgis_version: "2.5"
php_version: "7.3"
timestamp_directory: /nvme/data
osm_data_dir: /nvme/data/planet
flatnodes_dir: /nvme/data/flatnodes
tile_expiry_dir: /nvme/data/tileupdate
website_hostname_aliases:
  - buegelfalte.openrailwaymap.org
apache:
  configurations:
    php7.3-fpm.conf:
      enabled: yes
