debian_version: bookworm
pg_version: 15
php_version: "8.2"
postgis_version: 3

letsencrypt:
  ssl_domain: openrailwaymap.org
  certificate_alt_names: 'DNS:knallfrosch.openrailwaymap.org,DNS:openrailwaymap.org,DNS:www.openrailwaymap.org,DNS:tiles.openrailwaymap.org,DNS:a.tiles.openrailwaymap.org,DNS:b.tiles.openrailwaymap.org,DNS:c.tiles.openrailwaymap.org,DNS:api.openrailwaymap.org,DNS:blog.openrailwaymap.org'

apache:
  configurations:
    php8.2-fpm.conf:
      enabled: yes
  modules:
    remoteip:
    # Module tile not listed here because it is enabled during tileserver setup.
    rewrite:
    alias:
