pg_version: 17
postgis_version: 3
php_version: 8.4
debian_version: 'trixie'
osm2pgsql:
  output: "flex"
  osmium_filter: ""
  osmium_filter_file: "/opt/OpenRailwayMap-vector/import/osmium-tags-filter"
  style: "/opt/OpenRailwayMap-vector/import/openrailwaymap.lua"
  tag_transform: ""
  lua_path: "/opt/OpenRailwayMap-vector/build/tags.lua"

git:
  "OpenRailwayMap-vector":
    repo: "https://github.com/OpenRailwayMap/OpenRailwayMap-CartoCSS.git"
    version: "bb06fa8637d851addbf0e0da1c322ff8ca9931b1"
    directory: "/opt/OpenRailwayMap-vector"

tileserver:
  post_import_sql_scripts: []
  additional_indices: []
  vector: true
  styles:
    - standard
    - maxspeed
