apache:
  modules:
    proxy:
    proxy_uwsgi:
    alias:
  sites:
    mailman.conf:
      enabled: yes
      content: |
        <VirtualHost *:80>
            ServerName lists.openrailwaymap.org
            Include /etc/apache2/sites-available/redirect-http.inc
        </VirtualHost>
        <VirtualHost *:443>
            ServerName lists.openrailwaymap.org
            ServerAlias lists.orm-dev
        
            SSLEngine on
            SSLCertificateFile /etc/letsencrypt/openrailwaymap.org/openrailwaymap.org-chain.crt
            SSLCertificateKeyFile /etc/letsencrypt/openrailwaymap.org/domain.key
            SSLProtocol all -SSLv3 -TLSv1 -TLSv1.1
            SSLCipherSuite ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384
            SSLHonorCipherOrder off
            SSLSessionTickets off
        
            Include /etc/apache2/sites-available/mailman.inc
            Include /etc/mailman3/apache.conf
            RedirectMatch "^/$" "/mailman3"
            <Location /mailman3/hyperkitty/api>
                Require local
            </Location>
        </VirtualHost>
        
        <VirtualHost *:80>
            # requests by mailman3-hyperkitty (the archiver)
            ServerName 127.0.0.1
            ServerAlias localhost
            Include /etc/mailman3/apache.conf
            <Location /mailman3/hyperkitty/api>
                Require local
            </Location>
        </VirtualHost>
