#! /usr/bin/env python3

"""Fetch daily generated data from tirex-tiledir-check.
"""

import argparse
from enum import Enum
import json
import os
import sys


class ServiceStatus(Enum):
    OK = 0
    WARNING = 1
    CRITICAL = 2
    UNKNOWN = 3


def respond(status, message, measurements):
    if not measurements:
        line = "{}: {}\n".format(status.name, message)
    else:
        line = "{}: {} | {}\n".format(status.name, message, measurements)
    print(line)
    sys.exit(status.value)


def get_data(path):
    with open(path, "r") as f:
        json_data = json.load(f)
    return json_data


def format_measurement(k, v):
    return "'{}'={}".format(k, v)


def join_values(measurements):
    parts = []
    for m in measurements:
        parts.append(format_measurement(m[0], m[1]))
    return " ".join(parts)


parser = argparse.ArgumentParser(description="Monitoring plugin for tirex-tiledir-check results. This plugin reads the generated stats and supplies them to Icinga. It does not validate or check the retrieved numbers.")
parser.add_argument("-s", "--style", type=str, help="Style", required=True)
parser.add_argument("-d", "--dir", type=str, help="Path where the JOSN files generated by the nightly job are located.")
args = parser.parse_args()

json_path = os.path.join(args.dir, "tiles-{}.stats".format(args.style))
data = get_data(json_path)
result = []
try:
    for style, style_data in data.items():
        if style != args.style:
            respond(ServiceStatus.UNKNOWN, "Wrong style {} found in {}".format(style, json_path))
        for zoom in range(len(style_data)):
            result.append(("{}_{:02d}_count".format(style, zoom), style_data[zoom]["count"]))
            result.append(("{}_{:02d}_sumsize".format(style, zoom), style_data[zoom]["sumsize"]))
    respond(ServiceStatus.OK, "Tirex tile cache stats for style {}".format(args.style), join_values(result))
except KeyError as e:
    respond(ServiceStatus.UNKNOWN, "Could not parse JSON data: {}".format(e))
