# SPDX-License-Identifier: MIT
- name: Set variables depending on Debian version
  block:
    - set_fact:
        tile_cache_dir: "/var/lib/tirex/tiles"
        tirex_user: tirex
      when: 'debian_version == "buster"'
    - set_fact:
        tile_cache_dir: "/var/cache/tirex/tiles"
        tirex_user: _tirex
      when: 'debian_version != "buster"'

- name: Create database functions and views for the map style
  include_tasks: run_sql.yml
  loop:
    - '{{ cartocss_dir }}/sql/functions.sql'
    - '{{ cartocss_dir }}/sql/osm_carto_views.sql'
    - '{{ cartocss_dir }}/sql/get_station_importance.sql'

- name: Create indexes to boost up rendering
  become: true
  become_user: postgres
  postgresql_idx:
    db: '{{ osm_dbname }}'
    idxname: '{{ item.name }}'
    idxtype: gist
    columns: way
    cond: '{{ item.where }}'
    table: '{{ item.table }}'
  loop:
    - name: 'openrailwaymap_line_all_but_ab_raz_prop'
      where: "railway IN ('rail', 'tram', 'light_rail', 'subway', 'narrow_gauge', 'disused', 'construction')"
      table: planet_osm_line
    - name: 'openrailwaymap_line_low'
      where: "railway = 'rail' AND tags->'usage' IN ('main', 'branch') AND service IS NULL"
      table: planet_osm_line
    - name: 'openrailwaymap_line_med'
      where: "railway = 'rail' AND tags->'usage' = 'main' AND service IS NULL"
      table: planet_osm_line
    - name: 'openrailwaymap_electrification_signals'
      where: "railway = 'signal' AND tags ? 'railway:signal:electricity'"
      table: planet_osm_line

- name: Create database user for tile rendering
  become: true
  become_user: postgres
  postgresql_user:
    name: '{{ tirex_user }}'
    db: '{{ osm_dbname }}'

- name: 'GRANT SELECT ON ALL TABLES IN SCHEMA public TO tirex'
  become: true
  become_user: postgres
  postgresql_privs:
    role: '{{ tirex_user }}'
    type: table
    objs: ALL_IN_SCHEMA
    privs: 'SELECT'
    database: '{{ osm_dbname }}'

- name: Install Carto and build Mapnik XML style file
  block:
    - name: Set Carto path
      when: "debian_version == 'buster'"
      set_fact:
        carto_path: '{{ cartocss_dir }}/node_modules/carto/bin/carto'
    - name: Set Carto path
      when: "debian_version != 'buster'"
      set_fact:
        carto_path: 'carto'

    - name: Install Make and NPM using APT
      when: "debian_version == 'buster'"
      apt:
        name: [make, npm]
    - name: Install Carto using NPM
      when: "debian_version == 'buster'"
      become: yes
      become_user: osmimport
      npm:
        name: carto
        version: '1.2.0'
        path: '{{ cartocss_dir }}'
    - name: Install Carto using APT
      when: "debian_version != 'buster'"
      apt:
        name: [node-carto, make]

    - name: Build Mapnik XML style files
      become: yes
      become_user: osmimport
      make:
        chdir: '{{ cartocss_dir }}'
        target: all
        params:
          CARTO: '{{ carto_path }}'
      notify:
        - systemd reload tirex-backend-manager

- name: Create /var/www/tiles to avoid a2dismod and a2dissite (and their counterparts) return status code != 0 due to missing document root
  when: "debian_version == 'buster'"
  file:
    path: '/var/www/tiles'
    owner: root
    group: root
    state: directory
    mode: '0755'

- name: Install mod_tile, tirex-core and tirex-backend-mapnik
  block:
    - name: Install Tirex and mod_tile from self built packages
      when: "debian_version == 'buster'"
      apt:
        deb: '{{ item }}'
      loop:
        - '/root/packages/tirex-core_0.6.1_amd64.deb'
        - '/root/packages/tirex-backend-mapnik_0.6.1_amd64.deb'
        - '/root/packages/libapache2-mod-tile_0.4-12~precise2_amd64.deb'
    - name: Install Tirex and mod_tile from Debian repository
      when: "debian_version != 'buster'"
      apt:
        name: [tirex, libapache2-mod-tile]
  notify:
    # Tirex and Apache are only restarted/reloaded if Ansible had to change something on the remote host (i.e. we install new package)
    - systemd reload apache2
    - systemd restart tirex-backend-manager
    - systemd restart tirex-master

- name: Create symlink from /var/lib/mod_tile to tile cache directory
  file:
    src: '{{ tile_cache_dir }}'
    path: /var/lib/mod_tile
    state: link
    force: yes

- name: "Ensure that tile cache directory is owned by Tirex's user"
  file:
    path: '{{ tile_cache_dir }}'
    state: directory
    owner: '{{ tirex_user }}'
    group: '{{ tirex_user }}'
    mode: 0755
  notify:
    - systemd reload tirex-backend-manager
    - systemd reload tirex-master

- name: Changes to Tirex configuration on Debian Buster
  notify:
    - systemd reload tirex-backend-manager
  when: "debian_version == 'buster'"
  block:
    - name: 'Tirex: Change Mapnik plugin path in /etc/tirex/renderer/mapnik.conf'
      lineinfile:
        path: /etc/tirex/renderer/mapnik.conf
        regexp: '^plugindir=/usr/lib/mapnik/(3\.0/)?input/?$'
        line: 'plugindir=/usr/lib/mapnik/3.0/input/'

    - name: 'Tirex: Set syslog facility to daemon in /etc/tirex/renderer/mapnik.conf'
      lineinfile:
        path: /etc/tirex/renderer/mapnik.conf
        regexp: '^#? *syslog_facility=daemon$'
        line: 'syslog_facility=daemon'

    - name: 'Tirex: Change Mapnik fonts path in /etc/tirex/renderer/mapnik.conf'
      lineinfile:
        path: /etc/tirex/renderer/mapnik.conf
        regexp: '^fontdir=/usr/(lib/mapnik|share)/fonts/?$'
        line: 'fontdir=/usr/share/fonts/'

    - name: 'Tirex: Enable recursive search in Mapnik fonts path in /etc/tirex/renderer/mapnik.conf'
      lineinfile:
        path: /etc/tirex/renderer/mapnik.conf
        regexp: '^#?fontdir_recurse='
        line: 'fontdir_recurse=1'

- name: 'Tirex: Configure buckets'
  lineinfile:
    path: /etc/tirex/tirex.conf
    regexp: '^bucket +name=({{ item.bucket }}|{{ item.oldname }}) +minprio=\d+ +maxproc=\d+ +maxload=\d+$'
    line: 'bucket name={{ item.bucket }} minprio={{ item.minprio}} maxproc={{ item.maxproc }} maxload={{ item.maxload }}'
  loop:
    - bucket: live
      oldname: live
      minprio: 1
      maxproc: 4
      maxload: 20
      # Upstream minprio 10, maxproc 3, maxload 8
    - bucket: important
      oldname: important
      minprio: 10
      maxproc: 2
      maxload: 14
      # Does not exist upstream
    - bucket: expiredtiles
      oldname: expiredtiles
      minprio: 15
      maxproc: 2
      maxload: 9
      # Upstream called "background", minprio 20, maxproc 2, maxload 4
    - bucket: rerenderstyleupdate
      oldname: background
      minprio: 20
      maxproc: 2
      maxload: 4
  notify:
    - systemd reload tirex-master

- name: Install gawk
  apt:
    name: gawk

- name: Clone tileserver demonstration page repository
  git:
    dest: /var/www/tiles
    repo: https://github.com/geofabrik/tileserver-demosite.git
    version: 5571bb913905fba6def4eb194efdc80d4620cc42

- name: Configure demonstration page
  template:
    src: settings.js
    dest: /var/www/tiles/settings.js
    mode: 0644
    owner: root
    group: root

- name: Build demonstration page
  make:
    chdir: /var/www/tiles
    target: all

- name: Deactivate default tileserver page
  when: "debian_version == 'buster'"
  command:
    cmd: a2dissite tileserver_site.conf
    chdir: /etc/apache2/sites-available
    removes: '/etc/apache2/sites-enabled/tileserver_site.conf'
  notify:
    - systemd reload apache2

- name: Create directory for error tiles
  file:
    path: /var/www/tile-util
    owner: root
    group: root
    mode: 0755
    state: directory

- name: Copy error tiles to /var/www/tile-util
  copy:
    src: '{{ item }}'
    dest: '/var/www/tile-util/{{ item }}'
    owner: root
    group: root
    mode: 0644
  loop:
    - black.png
    - attribution-tile.png

- name: Enable Apache module tile
  apache2_module:
    name: tile
    state: present
  notify:
    - systemd reload apache2

- name: "Create /etc/tirex/renderer/mapnik"
  file:
    path: /etc/tirex/renderer/mapnik
    owner: root
    group: root
    state: directory
    mode: 0755

- name: Create Tirex configuration for all map styles
  copy:
    dest: '/etc/tirex/renderer/mapnik/{{ item }}.conf'
    owner: root
    group: root
    mode: 0664
    content: |
        name={{ item }}
        tiledir=/var/lib/tirex/tiles/{{ item }}
        minz=0
        maxz=19
        mapfile={{ cartocss_dir }}/{{ item }}.xml
        maxrequests=50
        tilesize=512
        scalefactor=2.0
        buffersize=50
  loop: "{{ tileserver.styles }}"
  notify:
    - systemd reload tirex-backend-manager
    - systemd reload tirex-master

- name: Create tile cache directories
  file:
    path: '/var/lib/tirex/tiles/{{ item }}'
    owner: '{{ tirex_user }}'
    group: '{{ tirex_user }}'
    mode: 0755
    state: directory
  loop: "{{ tileserver.styles }}"
  notify:
    - systemd reload tirex-backend-manager
    - systemd reload tirex-master

- name: systemd start and enable tirex-backend-manager.service
  systemd:
    name: tirex-backend-manager
    enabled: yes
    state: started

- name: systemd start and enable tirex-master.service
  systemd:
    name: tirex-backend-manager
    enabled: yes
    state: started

- name: Create Systemd service file for deleting old metatiles regularly
  copy:
    dest: /etc/systemd/system/delete_old_metatiles.service
    mode: 0644
    owner: root
    group: root
    content: |
      [Unit]
      Description=Delete old metatiles
      After=network.target

      [Service]
      Type=simple
      ExecStart=/bin/bash {{ tileserver_script_dir }}/scripts/delete_old_metatiles.sh
      User={{ tirex_user }}
      Group={{ tirex_user }}
      StandardOutput=journal
      StandardError=journal
      SyslogIdentifier=delete_old_metatiles
      Nice=+1
  notify:
    - systemd daemon-reload

- name: Write Systemd Timer for delete_old_metatiles.timer
  copy:
    dest: '/etc/systemd/system/delete_old_metatiles.timer'
    mode: 0644
    owner: root
    group: root
    content: |
      [Unit]
      Description=Delete old metatiles every month

      [Timer]
      OnUnitActiveSec=30d
      OnBootSec=15d
      Unit=delete_old_metatiles.service

      [Install]
      WantedBy=default.target
  notify:
    - systemd daemon-reload
    - systemd restart delete_old_metatiles.timer

- name: Enable update-data, rerender-lowzoom-tiles and delete_old_metatiles.timer
  systemd:
    name: "{{ item }}"
    enabled: yes
    state: started
  loop:
    - "update-data.timer"
    - "rerender-lowzoom-tiles.timer"
    - "delete_old_metatiles.timer"

- name: Create /usr/lib/nagios/plugins
  file:
    path: /usr/lib/nagios/plugins
    owner: root
    group: root
    mode: '0755'

- name: Copy monitoring plugin for mod_tile
  copy:
    src: 'monitoring/mod-tile/check_mod_tile.py'
    dest: '/usr/lib/nagios/plugins'
    owner: root
    group: root
    mode: '0755'

- debug: # noqa unnamed-task
    msg: 'Tirex is ready to render tiles now. Please start bulk-rendering of tiles on zoom levels 0 to 12 using the following command:\ntirex-batch --prio 15 map=standard,maxspeed,signals z=0-12 bbox=-180,-80,180,80'
