# SPDX-License-Identifier: MIT
- name: 'systemd reload postgresql'
  systemd:
    name: apache2
    state: reloaded
- name: 'systemd reload postfix'
  systemd:
    name: postfix
    state: reloaded
- name: 'systemd restart postfix'
  systemd:
    name: postfix
    state: restarted
- name: 'systemd restart mailman3'
  systemd:
    name: mailman3
    state: restarted
- name: 'systemd restart mailman3-web'
  systemd:
    name: mailman3-web
    state: restarted
- name: 'systemd restart amavisd-milter'
  systemd:
    name: amavisd-milter
    state: restarted
- name: 'systemd restart opendkim'
  systemd:
    name: opendkim
    state: restarted
- name: systemctl restart rspamd
  systemd:
    name: rspamd
    state: restarted
