# SPDX-License-Identifier: MIT
- name: Install required packages from APT
  apt:
    name:
      - postgresql-common
      - locales-all
      - unzip
      - zip
      - python3-pip
      - wget
      - php-fpm
      - apache2
      - python3-pil
      - python3-cairo
      - python3-ply
      - gettext

- name: Install pojson from Pip
  pip:
    executable: pip3
    name: pojson
    state: present

- name: Create directory for Git repository
  file:
    path: '{{ website_dir }}'
    owner: root
    group: root
    state: directory
    mode: '0755'

- name: Clone Git repository of the website
  register: website_git
  git:
    dest: '{{ website_dir }}'
    repo: https://github.com/OpenRailwayMap/OpenRailwayMap.git
    # We need to call it with force:yes because our database layout requires to overwrite api/config.json
    force: yes
    version: master

- name: Download and install Leaflet and its plugins
  make:
    chdir: '{{ website_dir }}'
    target: install-deps

- name: Build MapCSS styles, JOSM presets and locales
  when: website_git.changed
  make:
    chdir: '{{ website_dir }}/{{ item }}'
    target: all
  loop:
    - 'josm-presets'
    - 'styles'
    - 'locales'

- name: Create system user openrailwaymap to run the API
  user:
    name: openrailwaymap
    shell: '/usr/sbin/nologin'
    home: '{{ openrailwaymap_user_home }}'
    comment: 'OpenRailwayMap API user'
    password: '*'
    system: yes

- debug: # noqa unnamed-task
    msg: 'On Debian, the authentication method md5 is enabled for all users connecting from localhost via TCP/IP to any local database. Modify pg_hba.conf if your database is configured differently.'

- name: Create database user openrailwaymap for the API
  become: true
  become_user: postgres
  postgresql_user:
    name: openrailwaymap
    db: 'postgres'
    encrypted: yes
  notify:
    - systemd restart orm-api

- name: Install required packages from APT for API version 2
  apt:
    name:
      - python3-werkzeug
      - python3-psycopg2
      - apache2
      - libapache2-mod-wsgi-py3

- name: Create directory for Git repository
  file:
    path: '{{ api_v2.directory }}'
    owner: root
    group: root
    state: directory
    mode: '0755'

- name: Clone Git repository of the API
  git:
    dest: '{{ api_v2.directory }}'
    repo: https://github.com/OpenRailwayMap/OpenRailwayMap-api.git
    version: d030c50c6c38bb6117df5ac0d0cba3251be06a6f

- name: Create database extension Unaccent
  become: true
  become_user: postgres
  postgresql_ext:
    db: '{{ osm_dbname }}'
    name: 'unaccent'

- name: Create database views and indexes for the APIv2
  become: true
  become_user: osmimport
  community.postgresql.postgresql_script:
    login_user: osmimport
    db: '{{ osm_dbname }}'
    path: '{{ api_v2.directory }}/{{ item }}'
  loop:
    - 'prepare_facilities.sql'
    - 'prepare_milestones.sql'

- name: Enable updates of materialized views
  copy:
    src: update_api_views.sh
    dest: /opt/OpenRailwayMap-server-config/post-update.d/
    owner: root
    group: root
    mode: 0644

- name: Grant SELECT permission to user openrailwaymap
  become: true
  become_user: postgres
  ignore_errors: '{{ ansible_check_mode }}'
  postgresql_privs:
    role: openrailwaymap
    type: table
    objs: openrailwaymap_ref,openrailwaymap_facilities_for_search
    privs: 'SELECT'
    database: '{{ osm_dbname }}'

- name: Enable Apache modules proxy, proxy_http, headers, http2 and rewrite
  apache2_module:
    name: '{{ item }}'
    state: present
  loop:
    - 'proxy'
    - 'proxy_http'
    - 'headers'
    - 'wsgi'
    - 'http2'
  notify:
    - systemd restart apache2

- name: Ensure that files included by Apache configuration are present
  when: "'letsencrypt' in group_names"
  include_tasks: '../../../includes/redirect-and-acme-challenge-includes.yml'

- name: Add website and API VirtualHost configuration of Apache
  template:
    src: '{{ item }}'
    dest: '/etc/apache2/sites-available/{{ item }}'
    owner: root
    group: root
    mode: 0664
  loop:
    - 'www.openrailwaymap.org.inc'
    - 'www.openrailwaymap.org.conf'
    - 'api.openrailwaymap.org.inc'
    - 'api.openrailwaymap.org.conf'
  notify:
    - systemd reload apache2

- name: Enable Apache VirtualHost configuration for API and website
  command:
    cmd: 'a2ensite {{ item }}'
    chdir: /etc/apache2/sites-available
    creates: '/etc/apache2/sites-enabled/{{ item }}'
  loop:
    - www.openrailwaymap.org.conf
    - api.openrailwaymap.org.conf
  notify:
    - systemd reload apache2
