all:
  hosts:
    buegelfalte.openrailwaymap.org:
      ansible_become: yes
      apache2_logdir: /var/log/apache2
  vars:
    ansible_python_interpreter: python3
    ansible_user: root

  children:
    letsencrypt:
      hosts:
        buegelfalte.openrailwaymap.org
      vars:
        ssl_domain: openrailwaymap.org
        certificate_alt_names: 'DNS:buegelfalte.openrailwaymap.org,DNS:openrailwaymap.org,DNS:www.openrailwaymap.org,DNS:tiles.openrailwaymap.org,DNS:a.tiles.openrailwaymap.org,DNS:b.tiles.openrailwaymap.org,DNS:c.tiles.openrailwaymap.org,DNS:api.openrailwaymap.org,DNS:blog.openrailwaymap.org,DNS:lists.openrailwaymap.org'

    tileserver:
      hosts:
        buegelfalte.openrailwaymap.org:
      vars:
        website_hostname: www.openrailwaymap.org
        api_hostname: api.openrailwaymap.org
        website_dir: /var/www/www.openrailwaymap.org
        openrailwaymap_user_home: /srv/openrailwaymap

    blog:
      hosts:
        buegelfalte.openrailwaymap.org:
          blog:
            hostname: blog.openrailwaymap.org
            hostname_aliases: []
            directory: /var/www/blog

    munin_node:
      hosts:
        buegelfalte.openrailwaymap.org:
          ssl_domain: openrailwaymap.org
          accept_from: ['148.251.245.55', '2a01:4f8:192:81b6::2']
      vars:
        # Do not mention ip_ here, it is handled separately.
        munin_node_plugins:
          - {name: apache_accesses, dest: apache_accesses}
          - {name: apache_processes, dest: apache_processes}
          - {name: apache_volume, dest: apache_volume}
          - {name: postgres_autovacuum, dest: postgres_autovacuum}
          - {name: postgres_bgwriter, dest: postgres_bgwriter}
          - {name: postgres_checkpoints, dest: postgres_checkpoints}
          - {name: postgres_users, dest: postgres_users}
          - {name: postgres_xlog, dest: postgres_xlog}
          - {name: postgres_connections_db, dest: postgres_connections_db}
          - {name: postgres_connections_ALL, dest: postgres_connections_}
          - {name: postgres_cache_ALL, dest: postgres_cache_}
          - {name: postgres_locks_ALL, dest: postgres_locks_}
          - {name: postgres_oldest_prepared_xact_ALL, dest: postgres_oldest_prepared_xact_}
          - {name: postgres_prepared_xacts_ALL, dest: postgres_prepared_xacts_}
          - {name: postgres_querylength_ALL, dest: postgres_querylength_}
          - {name: postgres_scans_ALL, dest: postgres_scans_}
          - {name: postgres_size_ALL, dest: postgres_size_}
          - {name: postgres_transactions_ALL, dest: postgres_transactions_}
          - {name: postgres_tuples_ALL, dest: postgres_tuples_}
          - {name: mod_tile_fresh, dest: mod_tile_fresh}
          - {name: mod_tile_latency, dest: mod_tile_latency}
          - {name: mod_tile_response, dest: mod_tile_response}
          - {name: mod_tile_zoom, dest: mod_tile_zoom}
          - {name: tirex-status-active-requests, dest: tirex-status-active-requests}
          - {name: tirex-status-queued-requests, dest: tirex-status-queued-requests}
          - {name: tirex-status-queued-requests-age, dest: tirex-status-queued-requests-age}
          - {name: tirex-status-render-time, dest: tirex-status-render-time}
          - {name: tirex-status-requests-rendered, dest: tirex-status-requests-rendered}
          - {name: tirex-tiledir-diskusage-maxspeed, dest: tirex-tiledir-diskusage}
          - {name: tirex-tiledir-diskusage-signals, dest: tirex-tiledir-diskusage}
          - {name: tirex-tiledir-diskusage-standard, dest: tirex-tiledir-diskusage}
          - {name: tirex-tiledir-tileage-maxspeed, dest: tirex-tiledir-tileage}
          - {name: tirex-tiledir-tileage-signals, dest: tirex-tiledir-tileage}
          - {name: tirex-tiledir-tileage-standard, dest: tirex-tiledir-tileage}
          - {name: tirex-tiledir-tilecount-absolute-maxspeed, dest: tirex-tiledir-tilecount-absolute}
          - {name: tirex-tiledir-tilecount-absolute-signals, dest: tirex-tiledir-tilecount-absolute}
          - {name: tirex-tiledir-tilecount-absolute-standard, dest: tirex-tiledir-tilecount-absolute}
          - {name: tirex-tiledir-tilecount-relative-maxspeed, dest: tirex-tiledir-tilecount-relative}
          - {name: tirex-tiledir-tilecount-relative-signals, dest: tirex-tiledir-tilecount-relative}
          - {name: tirex-tiledir-tilecount-relative-standard, dest: tirex-tiledir-tilecount-relative}
        munin_node_ip_plugin: true
        munin:
          tirex_enabled: true

    backup_access:
      hosts:
        buegelfalte.openrailwaymap.org:
          backup_user_in_groups:
            - user: backup
              groups: list
          postgresql_backup_user:
            username: backup
            databases: ['mailman3web', 'mailman3']
      vars:
        backup_access:
          users:
            - name: backup
              ssh_pub_key: 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIF3sWWFwMR6Goke3hCYs0p2b/xQSUUmqNCV0gP86qocW access backups'

